services:
  rabbit:
    image: rabbitmq:3.8-management
    container_name: rabbit
    hostname: ${CURRENT_NODE_FQDN}
    restart: always
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./hosts:/etc/hosts
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbits
    environment:
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
    ports:
      - "80:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"

networks:
  rabbits:

volumes:
  rabbitmq_data:
